In [6]:
import cv2
import numpy as np
import pandas
import glob
import matplotlib.pyplot as plt
import os

In [7]:
%matplotlib inline

In [700]:
path_list_0 = glob.glob('.\\0\\*')
path_list_0

['.\\0\\ScreenShot00003.jpg',
 '.\\0\\ScreenShot00004.jpg',
 '.\\0\\ScreenShot00005.jpg',
 '.\\0\\ScreenShot00006.jpg',
 '.\\0\\ScreenShot00008.jpg',
 '.\\0\\ScreenShot00009.jpg',
 '.\\0\\ScreenShot00011.jpg',
 '.\\0\\ScreenShot00012.jpg',
 '.\\0\\ScreenShot00014.jpg',
 '.\\0\\ScreenShot00017.jpg',
 '.\\0\\ScreenShot00018.jpg',
 '.\\0\\ScreenShot00019.jpg',
 '.\\0\\ScreenShot00022.jpg',
 '.\\0\\ScreenShot00026.jpg',
 '.\\0\\ScreenShot00028.jpg',
 '.\\0\\ScreenShot00029.jpg',
 '.\\0\\ScreenShot00051.jpg',
 '.\\0\\ScreenShot00061.jpg',
 '.\\0\\ScreenShot00066.jpg',
 '.\\0\\ScreenShot00068.jpg',
 '.\\0\\ScreenShot00104.jpg',
 '.\\0\\ScreenShot00112.jpg',
 '.\\0\\ScreenShot00132.jpg',
 '.\\0\\ScreenShot00136.jpg',
 '.\\0\\ScreenShot00139.jpg',
 '.\\0\\ScreenShot00143.jpg',
 '.\\0\\ScreenShot00150.jpg',
 '.\\0\\ScreenShot00154.jpg',
 '.\\0\\ScreenShot00155.jpg',
 '.\\0\\ScreenShot00157.jpg',
 '.\\0\\ScreenShot00168.jpg',
 '.\\0\\ScreenShot00169.jpg',
 '.\\0\\ScreenShot00173.jpg',
 '.\\0\\Sc

In [701]:
# path_name_0 = [i.split('\\')[-1] for i in path_list_0]
# path_name_0

In [702]:
pwd = glob.glob('*')
pwd

['0', '1', '2', 'res_0', 'res_1', 'res_2', 'xgb.model', '缺陷分类.ipynb']

In [703]:
img_name = os.path.join('.\\',pwd[0],path_name_0[0])
img_name

'.\\0\\ScreenShot00003.jpg'

In [758]:
# 0文件夹修改大小
count = 1
for i in path_list_0:
    img_name = i
    img = cv2.imread(img_name,0)
    # 修改图片大小
    img = cv2.resize(img, (32, 32), interpolation=cv2.INTER_CUBIC)
    # print(img.shape)
    cv2.imwrite('.\\res_0\\' + str(count) + '.jpg',img)
    count += 1
    img = np.rot90(img)
    cv2.imwrite('.\\res_0\\' + str(count) + '.jpg',img)
    count += 1
    img = np.rot90(img)
    cv2.imwrite('.\\res_0\\' + str(count) + '.jpg',img)
    count += 1
    img = np.rot90(img)
    cv2.imwrite('.\\res_0\\' + str(count) + '.jpg',img)
    count += 1

In [759]:
# 1文件夹修改大小
path_list_1 = glob.glob('.\\1\\*')
path_list_1
# count = 1
for i in path_list_1:
    img_name = i
    img = cv2.imread(img_name,0)
    # 修改图片大小
    img = cv2.resize(img, (32, 32), interpolation=cv2.INTER_CUBIC)
    # print(img.shape)
    cv2.imwrite('.\\res_0\\' + str(count) + '.jpg',img)
    count += 1
    img = np.rot90(img)
    cv2.imwrite('.\\res_0\\' + str(count) + '.jpg',img)
    count += 1
    img = np.rot90(img)
    cv2.imwrite('.\\res_0\\' + str(count) + '.jpg',img)
    count += 1
    img = np.rot90(img)
    cv2.imwrite('.\\res_0\\' + str(count) + '.jpg',img)
    count += 1

In [897]:
# 2文件夹修改大小
path_list_1 = glob.glob('.\\2\\*')
path_list_1
count = 1
for i in path_list_1:
    img_name = i
    img = cv2.imread(img_name,0)
    # 修改图片大小
    img = cv2.resize(img, (32, 32), interpolation=cv2.INTER_CUBIC)
    # print(img.shape)
    cv2.imwrite('.\\res_2\\' + str(count) + '.jpg',img)
    count += 1
    cv2.imwrite('.\\res_2\\' + str(count) + '.jpg',img)
    count += 1
    cv2.imwrite('.\\res_2\\' + str(count) + '.jpg',img)
    count += 1

In [898]:
path_list_res_0 = glob.glob('.\\res_0\\*')
# path_list_res_0

In [899]:
# 转换0号对应的数据
list2 = []
for i in path_list_res_0:
    img_name = i
    img = cv2.imread(img_name,0)
    a1 = np.array(img)
    a2 = a1.reshape(1,-1)
    list1 = list(a2[0])
    list1.append(0)
    list2.append(list1)
X0 = np.array(list2)
X0

array([[17, 17, 23, ..., 16, 21,  0],
       [15, 16, 18, ..., 17, 23,  0],
       [22, 17, 21, ..., 24, 21,  0],
       ...,
       [23, 11, 14, ..., 10, 44,  0],
       [12, 11, 12, ..., 10, 13,  0],
       [44, 10, 14, ..., 11, 23,  0]])

In [900]:
# 转换1号对应的数据
# path_list_res_1 = glob.glob('.\\res_1\\*')
# path_list_res_1
# # list2 = []
# for i in path_list_res_1:
#     img_name = i
#     img = cv2.imread(img_name,0)
#     a1 = np.array(img)
#     a2 = a1.reshape(1,-1)
#     list1 = list(a2[0])
#     list1.append(1)
#     list2.append(list1)
# X1 = np.array(list2)
# X1

In [901]:
# 转换2号对应的数据
path_list_res_2 = glob.glob('.\\res_2\\*')
path_list_res_2
# list2 = []
for i in path_list_res_2:
    img_name = i
    img = cv2.imread(img_name,0)
    a1 = np.array(img)
    a2 = a1.reshape(1,-1)
    list1 = list(a2[0])
    list1.append(1)
    list2.append(list1)
X2 = np.array(list2)
X2

array([[17, 17, 23, ..., 16, 21,  0],
       [15, 16, 18, ..., 17, 23,  0],
       [22, 17, 21, ..., 24, 21,  0],
       ...,
       [15, 13, 14, ...,  9, 16,  1],
       [15, 13, 14, ...,  9, 16,  1],
       [15, 13, 14, ...,  9, 16,  1]])

In [902]:
X2.shape

(3539, 1025)

In [903]:
def minus_min(x):
    s = x[:, :-1]
    for i in s:
        i -= 0
    return x
X = minus_min(X2)
X

array([[17, 17, 23, ..., 16, 21,  0],
       [15, 16, 18, ..., 17, 23,  0],
       [22, 17, 21, ..., 24, 21,  0],
       ...,
       [15, 13, 14, ...,  9, 16,  1],
       [15, 13, 14, ...,  9, 16,  1],
       [15, 13, 14, ...,  9, 16,  1]])

In [904]:
X.shape

(3539, 1025)

In [905]:
from sklearn.model_selection import train_test_split
import xgboost as xgb
from sklearn.metrics import mean_squared_error
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics import f1_score,precision_score,recall_score,accuracy_score

In [906]:
x_train, x_test, y_train, y_test = train_test_split(X[:,:-1], X[:,-1], 
                                                    test_size = 0.1, random_state = 28)
print('训练数据样本数量：{0},测试样本数量：{1}'.format(x_train.shape[0], x_test.shape[0]))

训练数据样本数量：3185,测试样本数量：354


In [907]:
x_train.shape

(3185, 1024)

In [908]:
# from sklearn.decomposition import PCA
# pca = PCA(n_components = 64)
# pca.fit(x_train)
# print(pca.mean_)
# print(pca.components_)
# x_train = pca.transform(x_train)
# pca.fit(x_test)
# x_test = pca.transform(x_test)

In [909]:
# 将数据转为CGBoost可用的数据类型
dtrain = xgb.DMatrix(x_train, label = y_train)
dtest = xgb.DMatrix(x_test)

In [910]:
# XGBoost构建模型
# 1，参数设定
params={
'booster':'gbtree',
'objective':'multi:softmax',
# 'booster':'gblinear',
# 'objective': 'reg:logistic', #二分类的问题
'num_class':2, # 分类个数
'gamma':0.1,  # 用于控制是否后剪枝的参数,越大越保守，一般0.1、0.2这样子。
'max_depth':30, # 构建树的深度，越大越容易过拟合
'lambda':4,  # 控制模型复杂度的权重值的L2正则化项参数，参数越大，模型越不容易过拟合。
'subsample':0.8, # 随机采样训练样本
'colsample_bytree':0.8, # 生成树时进行的列采样
'min_child_weight':3,
# 这个参数默认是 1，是每个叶子里面 h 的和至少是多少，对正负样本不均衡时的 0-1 分类而言
#，假设 h 在 0.01 附近，min_child_weight 为 1 意味着叶子节点中最少需要包含 100 个样本。
#这个参数非常影响结果，控制叶子节点中二阶导的和的最小值，该参数值越小，越容易 overfitting。
'silent':0 ,#设置成1则没有运行信息输出，最好是设置为0.
'eta': 0.0001, # 如同学习率
'seed':5000
# 'nthread':7,# cpu 线程数
#'eval_metric': 'auc'
}
num_round = 8
# 2，模型训练
bst = xgb.train(params, dtrain, num_round)
# 3，模型保存
bst.save_model('xgb.model')

[15:09:29] d:\build\xgboost\xgboost-0.80.git\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 160 extra nodes, 2 pruned nodes, max_depth=23
[15:09:29] d:\build\xgboost\xgboost-0.80.git\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 152 extra nodes, 0 pruned nodes, max_depth=23
[15:09:29] d:\build\xgboost\xgboost-0.80.git\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 160 extra nodes, 2 pruned nodes, max_depth=17
[15:09:29] d:\build\xgboost\xgboost-0.80.git\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 150 extra nodes, 2 pruned nodes, max_depth=19
[15:09:29] d:\build\xgboost\xgboost-0.80.git\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 152 extra nodes, 0 pruned nodes, max_depth=18
[15:09:29] d:\build\xgboost\xgboost-0.80.git\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 148 extra nodes, 2 pruned nodes, max_depth=21
[15:09:29] d:\build\xgboost\xgboost-0.80.git\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 142 extra 

In [911]:
# XGBoost模型预测
y_pred = bst.predict(dtest)
print(mean_squared_error(y_pred, y_test))
dtrain1 = xgb.DMatrix(x_train)
y_pred1 = bst.predict(dtrain1)
print("训练集准确率为:{}%" .format(accuracy_score(y_train, y_pred1)*100))

0.05084745762711865
训练集准确率为:99.78021978021978%


In [912]:
# 4.加载模型
bst2 = xgb.Booster()
bst2.load_model('xgb.model')
# 5，使用加载模型进行预测
y_pred2 = bst2.predict(dtest)
print(mean_squared_error(y_pred2, y_test))
print(y_pred2)

0.05084745762711865
[1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 1.
 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1.
 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0.
 0. 0. 1. 0. 0. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 0. 0. 0.
 1. 0. 0. 1. 0. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 0. 1. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1. 0.
 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.
 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 1. 0.
 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 1.
 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 1. 1. 0. 1. 1.
 1. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 1. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 

In [913]:
# 效果评估
print("测试集准确率为:{}%" .format( round(accuracy_score(y_test, y_pred2)*100,5)))
print("精准率为:%.5f" % precision_score(y_test, y_pred2))
print("召回率为:%.5f" % recall_score(y_test, y_pred2))
print("F1值为:%.5f" % f1_score(y_test, y_pred2))

测试集准确率为:94.91525%
精准率为:0.90625
召回率为:0.95082
F1值为:0.92800


In [915]:
# 看看那些出错了
for i in range(len(y_test)):
    if y_test[i] != y_pred2[i]:
        s = x_test[i]
        s.shape = (32, 32)
        cv2.imwrite('.\\res\\' + str(i) + '.jpg',s)